pub mod asset;
pub mod glossary;
pub mod package;
pub mod bibliography;
pub mod build_engine;
pub mod commands;
pub mod dependency_graph;
pub mod diagnostics;
pub mod events;
pub mod plugin;
pub mod security;
pub mod template_engine;
pub mod exporter;
pub mod compiler;
pub mod element;
pub mod error;
pub mod generator;
pub mod postflight;
pub mod profile;
pub mod project;
pub mod reference;
pub mod schema;
pub mod system;
pub mod template;
pub mod texis_project;
pub mod validator;

pub use compiler::{CompilationBackend, CompilationOptions, CompilationResult};
pub use error::{CoreError, CoreResult};
pub use generator::LaTeXGenerator;
pub use postflight::{PdfChecker, PdfPostflightResult};
pub use profile::model::Profile;
pub use element::model::Element;
pub use project::model::{ProjectModel, ProjectSection, ContentBlock};
pub use validator::report::ValidationReport;
